### PR TITLE
Add michaelpumo.com

### PR DESCRIPTION
**Pull request by michaelpumo**
Simply adding my portfolio website. Thanks!

### CODE REVIEW

**Comment by HZooly** [comment]
Hey @michaelpumo ! I love the effects, layout, and colors. Stunning website!
Thanks for formatting previous entry too haha

**Comment by michaelpumo** [comment]
> Hey @michaelpumo ! I love the effects, layout, and colors. Stunning website!
> Thanks for formatting previous entry too haha

Thank you for the kind words!

No worries about the formatting. I'm OCD on that kinda thing and felt nobody would mind. 🤣

Keep up the good work on the gallery and thanks for the merge!

**Comment by michaelpumo** [comment]
Is the screenshot automated? I just saw that it's missed off a few things, presumably because it was animating in. No huge issue, just an FYI!

**Comment by HZooly** [comment]
Yep screenshot is automatically taken with https://www.npmjs.com/package/capture-website, and Puppeteer wrapper!

**Pull request merged**
